### ISSUE TITLE
Invalid language with the Babel package.

### ISSUE THREAD

**Issue by gallandarakhneorg** [gallandarakhneorg/tex-upmethodology#24]
When compiling an english document, the following error occurs:
```
 
! Package babel Error: You haven't defined the language french yet!
 
See the babel package document for explanation.
Type H <return> for imediate help.
 
1.1411 \iflanguage{french}
                                           {
?
```

**Comment by gallandarakhneorg** [comment]
The uses of the Balbel macro \iflanguage are replaced by an test on the internal macro \upmcurrentlang.

**Comment by lichao8601** [comment]
I have complated my script with the templates updated, but this resutl anthter similar error:

! Package babel Error: You haven't defined the language french yet!

See the babel package document for explanation.
Type H <return> for imediate help.

1.21 \select@language{french}

**Comment by gallandarakhneorg** [comment]
I need the ".log" file, and the preamble of your LaTeX document.

**Comment by lichao8601** [comment]
Here is my log file.
 
Date: Fri, 24 Apr 2015 04:47:16 -0700

**Comment by lichao8601** [comment]
The issue is solved. I compiled the script in french for the first time, it is the file ".aux" who leads to the error. Therefore I delet it and run it again, the error disappars. Thanks for your help!

**Comment by gallandarakhneorg** [comment]
You're welcome.

I recommend you to use [AutoLaTeX](http://www.arakhne.org/autolatex) for helping you to manage the LaTeX compilation process.
